name: Trigger auto deployment for container2ly

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ deploy ]
    paths:
    - '**'
    - '.github/workflows/container2ly-AutoDeployTrigger-fb376ace-5eb8-4ee4-bfe2-d71f055e470c.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.CONTAINER2LY_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER2LY_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: v-luanyi@microsoft.com/container2ly:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINER2LY_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container2ly -g LuanYI --server docker.io --username  ${{ secrets.CONTAINER2LY_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINER2LY_REGISTRY_PASSWORD }}
            az containerapp update -n container2ly -g LuanYI --image v-luanyi@microsoft.com/container2ly:${{ github.sha }}
